apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    k8s.io/path: https://github.com/MalluruMamatha/k8-resources
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almaLinux:9
