apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      request: ## request is always = to limit or less than limit
        cpu: "250m"
        memory: "64Mi"
      limit:
        cpu: "500m"
        memory: "85Mi"