apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: nginx
    image: nginx
data:
  cloud: "AWS"
  course: "kuberneties"
  github: "https://github.com/MalluruMamatha/k8-resources"