apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    name: nginx
    image: nginx
env:
- name: cloud
  valueFrom:
    configMapKeyRef:
      name: configmap-demo
      key: cloud
- name: course
  valueFrom:
    configMapKeyRef:
      name: configmap-demo
      key: course


        

