apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
  ### refering each evn variable here from the configmap file
    # env:
    # - name: cloud
    #   valueFrom:
    #     configMapKeyRef:
    #       name: configmap-demo
    #       key: cloud
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: configmap-demo
    #       key: course
  #### if you want to refer the entire configmap file
    envFrom:
    - configMapRef:
        name: configmap-demo
          


        

