apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    name: nginx
    image: nginx
env:
- name: frontend
  valueFrom:
    configMapKeyRef:
      name: configmap-demo
      key: cloud
      key: course


        

