apiVersion: v1
kind: Service
metadata:
  name: service-np
spec:
  type: NodePort
  selector:   # Select Pods with the following labels
    project: expense
    environment: dev
  ports:
  - protocol: TCP
    port: 80       # Port on the Service
    targetPort: 80
    nodePort: 32760